Repository GSG-G13/NFT, pull requests merged in 2023-05, with the labels that each got.

#2 file structure
  .eslintrc.js
  .gitignore
  client/.eslintrc.cjs
  client/.gitignore
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/vite.svg
  client/src/index.css
  client/src/main.jsx
  client/vite.config.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/.gitkeep
  server/controllers/index.js
  server/db/.gitkeep
  server/db/config/.gitkeep
  server/db/queries/.gitkeep
  server/index.js
  server/middleware/.gitkeep
  server/routes/.gitkeep
  server/utils/.gitkeep
Labels: done

#6 finish connection
  package-lock.json
  package.json
  server/db/config/build.js
  server/db/config/connection.js
Labels: in-progress

#9 db edit
  server/db/config/build.sql
Labels: done

#12 create file app
  package.json
  server/app.js
  server/index.js
Labels: waiting-review

#15 handler errors
  server/controllers/Errors/clientError.js
  server/controllers/Errors/index.js
  server/controllers/Errors/serverError.js
Labels: done

#18 13 create react landingpage
  client/all.min.css
  client/index.html
  client/src/assets/images/044460150547103.62fc32b4dc2a0.jpg
  client/src/assets/images/1d9951150547103.62fc32b4de209.jpg
  client/src/assets/images/20033a150547103.62fc32b4e1637.jpg
  client/src/assets/images/2aa457150547103.62fc32b4e21a7.jpg
  client/src/assets/images/Untitled-1.png
  client/src/assets/images/Untitled-2.png
  client/src/assets/images/Untitled-3.png
  client/src/assets/images/a092e5150547103.62fc32b4db82f.jpg
  client/src/assets/images/a335ec150547103.62fc32b4dcd39(1).jpg
  client/src/assets/images/a7f587133374601.Y3JvcCw1ODMsNDU2LDgyNCwzNw.png
  client/src/assets/images/b84f72132018981.Y3JvcCwzMDAwLDIzNDYsMCwyNzQ.jpg
  client/src/assets/images/certified.png
  client/src/assets/images/e51a64150547103.62fc32b4df8b6.jpg
  client/src/assets/videos/landing_page_3.mp4
  client/src/components/Header.jsx
  client/src/components/Main.jsx
  client/src/components/Nav.jsx
  client/src/components/header.css
  client/src/components/main.css
  client/src/components/nav.css
  client/src/main.jsx
  client/src/routes/Signup/index.jsx
  client/src/routes/Signup/sign.css
  client/src/routes/Signup/sign.jsx
  client/src/routes/landingPage/Index.jsx
  client/src/routes/landingPage/index.css
  client/webfonts/fa-brands-400.ttf
  client/webfonts/fa-brands-400.woff2
  client/webfonts/fa-regular-400.ttf
  client/webfonts/fa-regular-400.woff2
  client/webfonts/fa-solid-900.ttf
  client/webfonts/fa-solid-900.woff2
  client/webfonts/fa-v4compatibility.ttf
  client/webfonts/fa-v4compatibility.woff2
Labels: done

#20 Signup back
  client/package-lock.json
  client/package.json
  client/src/main.jsx
  client/src/routes/Signup/sign.jsx
  client/vite.config.js
  server/app.js
  server/controllers/user/signup.js
  server/db/config/build.sql
  server/db/config/connection.js
  server/db/queries/signupQuery.js
  server/routes/signup/index.js
  server/utils/jwt/generateToken.js
  server/utils/jwt/index.js
  server/utils/validation/index.js
  server/utils/validation/signupSchema.js
Labels: done

#21 finish fake data
  client/src/routes/Carts/Cart.jsx
Labels: waiting-review

#28 Loginback
  client/src/assets/images - Shortcut.lnk
  client/src/routes/Login/index.jsx
  client/src/routes/Signup/sign.jsx
  server/controllers/user/login.js
  server/controllers/user/signup.js
Labels: done

#34 cart
  client/src/components/Cart.jsx
  client/src/main.css
  client/src/main.jsx
  client/src/routes/Cart/index.css
  client/src/routes/Cart/index.jsx
  client/src/routes/Carts/Cart.css
  client/src/routes/Carts/Cart.jsx
  client/src/routes/Carts/images/edit.png
  client/src/routes/Login/index.jsx
  client/src/routes/Signup/index.jsx
  client/src/routes/Signup/signup.css
  client/src/routes/Signup/signup.jsx
  client/src/routes/landingPage/Index.jsx
  client/src/routes/landingPage/index.css
  client/vite.config.js
Labels: waiting-review

#38 Admin add products
  client/src/main.jsx
  client/src/routes/production/Products.jsx
  client/src/routes/production/products.css
  client/vite.config.js
  server/app.js
  server/controllers/product/addProduct.js
  server/controllers/product/index.js
  server/controllers/user/login.js
  server/controllers/user/products.js
  server/controllers/user/signup.js
  server/db/config/build.sql
  server/db/config/fakeData.sql
  server/db/queries/addProductQuery.js
  server/db/queries/getUserPassword.js
  server/middleware/.gitkeep
  server/middleware/checkAuth.js
  server/routes/productRouter/index.js
  server/routes/userRouter/index.js
  server/utils/jwt/index.js
Labels: waiting-review

#44 finish logout
  client/src/components/Nav.jsx
  client/src/components/nav.css
  server/app.js
  server/db/config/fakeData.sql
Labels: waiting-review

#45 finish cart
  client/src/routes/Login/index.jsx
  client/src/routes/Signup/sign.jsx
  client/src/routes/Signup/signup.css
  server/controllers/cart/getCart.js
  server/controllers/cart/postCart.js
  server/controllers/user/products.js
  server/db/config/build.sql
  server/db/config/fakeData.sql
  server/db/queries/cart/postCartQuery.js
  server/db/queries/getProductsQuery.js
  server/db/queries/getUserPassword.js
Labels: waiting-review

#46 fix admin add product
  server/db/config/fakeData.sql
  server/db/queries/addProductQuery.js
Labels: waiting-review

#47 add example.env file
  example.env
Labels: waiting-review

#49 add README.md file
  README.md
  client/src/routes/production/Products.jsx
  server/db/queries/cart/updateCartQuery.js
Labels: done

#51 add paginition feature
  client/src/components/Main.jsx
  client/src/components/Pagination.css
  client/src/components/Pagination.jsx
  client/src/routes/production/Products.jsx
  server/controllers/user/products.js
  server/db/queries/getProductsNuberQuery.js
  server/db/queries/getProductsQuery.js
Labels: done

#53 make some style for signup and login
  client/src/components/Nav.jsx
  client/src/routes/Login/index.jsx
  client/src/routes/Signup/sign.jsx
  client/src/routes/Signup/signup.css
Labels: waiting-review

#56 finish facke data
  server/db/config/fakeData.sql
Labels: waiting-review

#55 update css style login and sign up
  client/src/components/Nav.jsx
  client/src/components/nav.css
  client/src/routes/Login/index.jsx
  client/src/routes/Signup/sign.jsx
  client/src/routes/Signup/signup.css
  server/app.js
  server/middleware/checkAuth.js
  server/routes/userRouter/index.js
  server/utils/jwt/verifyToken.js
Labels: done

#60 handlerLogoutServer
  server/controllers/user/index.js
  server/controllers/user/logout.js
  server/routes/userRouter/index.js
Labels: waiting-review
